// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDWOq9yYeDQM-BMiNxxFrFFn7ctF2a7BU',
    appId: '1:435627390355:web:32690d27020c3c4a64a466',
    messagingSenderId: '435627390355',
    projectId: 'flutter-project-620cc',
    authDomain: 'flutter-project-620cc.firebaseapp.com',
    storageBucket: 'flutter-project-620cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA3pfliz9YcmAACvAXBcxj5M5hppgv-og',
    appId: '1:435627390355:android:caa39f0547808fec64a466',
    messagingSenderId: '435627390355',
    projectId: 'flutter-project-620cc',
    storageBucket: 'flutter-project-620cc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDWOq9yYeDQM-BMiNxxFrFFn7ctF2a7BU',
    appId: '1:435627390355:web:9cfb6da529315e4e64a466',
    messagingSenderId: '435627390355',
    projectId: 'flutter-project-620cc',
    authDomain: 'flutter-project-620cc.firebaseapp.com',
    storageBucket: 'flutter-project-620cc.firebasestorage.app',
  );
}
